name: Purge GH images cache

on: workflow_dispatch

jobs:
  purge-images-cache:
    name: Purge cached images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Purge README Images
        run: make purge
